spring:
  data:
    mongodb:
      uri: mongodb://shivani:123@localhost:27017/nitification?authSource=admin&authMechanism=SCRAM-SHA-256
#      host: localhost
#     port: 27017
#     username: shivani
#     password: 123
#     authentication-database: admin
#     database: customer

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: orderGroup,paymentGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.microservices.notification.order.OrderConfirmation, paymentConfirmation:com.microservices.notification.payment.PaymentConfirmation

  mail:
    host: localhost
    port: 1025
    username: shivani
    password: 123
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8094